Отрисовано окно для отправки сообщений
vdovindv/2019-2-Track-Frontend-D-Vdovin pull request #2
Opened 2019-10-27 16:09 UTC by vdovindv

# Домашнее задание № 2
Прошу @chexex проверить его.
Что было сделано:
*сверстана страница для отправки сообщений
*написан класс  messageObj для отображения сообщений в окне
*не получилось настроить Eslint

2019-10-28 05:18 UTC, martinkomitsky commented
@vdovindv прошу добавлять в заголовок PR номер ДЗ

2019-10-28 08:37 UTC, vdovindv commented
Можете посмотреть конфиги для линтера, пожалуйста? Вроде бы сделал все, как в инструкции на сайте, но сам линетр не может загрузиться почему-то

2019-10-28 14:41 UTC, priver requested changes

2019-10-28 14:41 UTC, priver commented on web-components/src/components/MessageForm.js
> +      const divFormatMessageContainer = document.createElement('div');
нужно сделать отдельный компонент для сообщений

2019-10-28 14:55 UTC, vdovindv commented on web-components/src/components/MessageForm.js
> +      const divFormatMessageContainer = document.createElement('div');
В смысле контейнер?

2019-10-29 09:48 UTC, priver commented on web-components/src/components/MessageForm.js
> +      const divFormatMessageContainer = document.createElement('div');
в смысле веб-компонент. такой же как `message-form` или `form-input` только представляющий одно сообщение. создавать через `const message = document.createElement('message')`, параметры передавать через `message.setAttribute()`

2019-10-29 13:31 UTC, vdovindv commented on web-components/src/components/MessageForm.js
> +      const divFormatMessageContainer = document.createElement('div');
Вметсо трех div сделать один компонент message и там уже время и текст сообщения выводить?

2019-10-31 10:00 UTC, priver commented on web-components/src/components/MessageForm.js
> +      const divFormatMessageContainer = document.createElement('div');
да

2019-11-13 05:09 UTC, martinkomitsky commented
@vdovindv есть новости?

2019-12-17 05:52 UTC, martinkomitsky commented
К сожалению, закрываю. Нет прогресса.

2019-12-17 05:52 UTC, closed without merging